-- ============================================================
-- 15_lol_esports_data.sql
-- Oracle's Elixir pro esports match CSV data.
-- Source of truth: lolesports_data_import.py — the COPY column
--                  list is the definitive column set (overrides
--                  the original DDL file which was missing
--                  pick1-5, void_grubs, opp_void_grubs, gpr,
--                  and at-20/at-25 snapshot columns, and had
--                  typos: visionscorre, totalgoal, earnedgpm)
-- Notes:
--   - Schema is "lol", table is esports_data (Python is
--     authoritative; the DDL file used schema "esports" and
--     table name "game_data" which differ from live usage).
--   - "team kpm", "earned gpm", "dragons (type unknown)",
--     "total cs" retain quoted names to match CSV headers.
--   - No primary key declared; table is bulk-truncated and
--     reloaded on each import run.
-- ============================================================

CREATE TABLE "lol".esports_data
(
    gameid                    varchar,
    datacompleteness          varchar,
    url                       text,
    league                    varchar,
    "year"                    int,
    split                     varchar,
    playoffs                  boolean,
    "date"                    date,
    game                      smallint,
    patch                     varchar,
    participantid             smallint,
    side                      varchar,
    "position"                varchar,
    playername                varchar,
    playerid                  varchar,
    teamname                  varchar,
    teamid                    varchar,
    champion                  varchar,
    ban1                      varchar,
    ban2                      varchar,
    ban3                      varchar,
    ban4                      varchar,
    ban5                      varchar,
    pick1                     varchar,
    pick2                     varchar,
    pick3                     varchar,
    pick4                     varchar,
    pick5                     varchar,
    gamelength                real,
    "result"                  boolean,
    kills                     real,
    deaths                    real,
    assists                   real,
    teamkills                 real,
    teamdeaths                real,
    doublekills               real,
    triplekills               real,
    quadrakills               real,
    pentakills                real,
    firstblood                boolean,
    firstbloodkill            boolean,
    firstbloodassist          boolean,
    firstbloodvictim          boolean,
    "team kpm"                real,
    ckpm                      real,
    firstdragon               boolean,
    dragons                   real,
    opp_dragons               real,
    elementaldrakes           real,
    opp_elementaldrakes       real,
    infernals                 real,
    mountains                 real,
    clouds                    real,
    oceans                    real,
    chemtechs                 real,
    hextechs                  real,
    "dragons (type unknown)"  real,
    elders                    real,
    opp_elders                real,
    firstherald               boolean,
    heralds                   real,
    opp_heralds               real,
    void_grubs                real,
    opp_void_grubs            real,
    firstbaron                boolean,
    barons                    real,
    opp_barons                real,
    firsttower                boolean,
    towers                    real,
    opp_towers                real,
    firstmidtower             boolean,
    firsttothreetowers        boolean,
    turretplates              real,
    opp_turretplates          real,
    inhibitors                real,
    opp_inhibitors            real,
    damagetochampions         real,
    dpm                       real,
    damageshare               real,
    damagetakenperminute      real,
    damagemitigatedperminute  real,
    wardsplaced               real,
    wpm                       real,
    wardskilled               real,
    wcpm                      real,
    controlwardsbought        real,
    visionscore               real,
    vspm                      real,
    totalgold                 real,
    earnedgold                real,
    "earned gpm"              real,
    earnedgoldshare           real,
    goldspent                 real,
    gspd                      real,
    gpr                       real,
    "total cs"                real,
    minionkills               real,
    monsterkills              real,
    monsterkillsownjungle     real,
    monsterkillsenemyjungle   real,
    cspm                      real,
    goldat10                  real,
    xpat10                    real,
    csat10                    real,
    opp_goldat10              real,
    opp_xpat10                real,
    opp_csat10                real,
    golddiffat10              real,
    xpdiffat10                real,
    csdiffat10                real,
    killsat10                 real,
    assistsat10               real,
    deathsat10                real,
    opp_killsat10             real,
    opp_assistsat10           real,
    opp_deathsat10            real,
    goldat15                  real,
    xpat15                    real,
    csat15                    real,
    opp_goldat15              real,
    opp_xpat15                real,
    opp_csat15                real,
    golddiffat15              real,
    xpdiffat15                real,
    csdiffat15                real,
    killsat15                 real,
    assistsat15               real,
    deathsat15                real,
    opp_killsat15             real,
    opp_assistsat15           real,
    opp_deathsat15            real,
    goldat20                  real,
    xpat20                    real,
    csat20                    real,
    opp_goldat20              real,
    opp_xpat20                real,
    opp_csat20                real,
    golddiffat20              real,
    xpdiffat20                real,
    csdiffat20                real,
    killsat20                 real,
    assistsat20               real,
    deathsat20                real,
    opp_killsat20             real,
    opp_assistsat20           real,
    opp_deathsat20            real,
    goldat25                  real,
    xpat25                    real,
    csat25                    real,
    opp_goldat25              real,
    opp_xpat25                real,
    opp_csat25                real,
    golddiffat25              real,
    xpdiffat25                real,
    csdiffat25                real,
    killsat25                 real,
    assistsat25               real,
    deathsat25                real,
    opp_killsat25             real,
    opp_assistsat25           real,
    opp_deathsat25            real
);
